runtime: python311
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  max_idle_instances: 2
  min_pending_latency: 300ms
  max_concurrent_requests: 1  # 1ワーカープロセスでの動作設定（app.yamlは1プロセス1スレッドに変更 2023-08-29）

app_engine_apis: true
# default_expiration: '4d 5h'

env_variables:
  MEMCACHE_USE_CROSS_COMPATIBLE_PROTOCOL: 'True'
  NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: 'True'
  GAE_USE_SOCKETS_HTTPLIB: 'true'
  SATERAITO_SET_SINGLETHREAD_MODE: 'True'  # defaultサービスをF1かつシングルスレッドで動作させる 2023-08-29

# 1ワーカープロセスでの動作設定（1プロセス4スレッド） --> app.yamlは1プロセス1スレッドに変更 2023-08-29
entrypoint: gunicorn --timeout 0 -b :$PORT --workers 1 --threads 4 main:app

inbound_services:
- warmup

handlers:

- url: /css
  static_dir: css
  expiration: 10s

- url: /js
  static_dir: js
  expiration: 10s

- url: /images
  static_dir: images
  expiration: 1d

- url: /images
  static_dir: images
  expiration: 1d

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  expiration: 1d

- url: /static/frontend/assets/(.*\.js)$
  static_files: static/frontend/assets/\1
  upload: static/frontend/assets/(.*\.js)$
  mime_type: text/javascript
  
- url: /static
  static_dir: static
  # expiration: 1d

- url: /(.*)
  script: auto
  secure: always
