#!/usr/bin/python
# coding: utf-8


'''
sateraito_black_list.py

@since: 2012-07-11
@version: 2023-11-15

@author: Akitoshi Abe
'''

DOMAINS_TO_DISABLE = [

	# added 2023-11-15
	'ux.kddi.com',
	'wiseinfinity.com',
	'newson.co.jp',
	'tobutoptours.net',
	'eternal-story.com',
	'aicross.co.jp',
	'okato.co.jp',
	'sohatsu.or.jp',
	'freshnessburger.co.jp',
	'sakura-39.jp',
	'water-and-life.biz',
	'gaisousenkameet.com',
	'techno-fc.com',
	'artkagaku.co.jp',
	'gt.edl.co.jp',
	'npkcargo.co.jp',
	'redhorse.com.hk',
	'test.dainichi-net.co.jp',
	'gotohya.co.jp',
	# added 2023-10-26
	'polite-fun.com',
	'somobile.co.jp',
	'st.musashi.ac.jp',
	'kbdevice.com',
	'nsb.jp',
	'nagaoka-mint.co.jp',
	'shinchouji.jp',
	'machicre.co.jp',
	'shinnichi-kochi.work',
	'ja-ces.info',
	'tsukuruba.com',
	'test-a.unilabo.tokyo',
	'wappa-kaigo.com',
	'sanko-ib.co.jp',
	'educal-motivations.com',
	'seikodoclouds.com',
	'mk-p.info',
	# added 2023-10-03
	'taisei-hr.co.jp',
	'cdg.co.jp',
	'chubushiryo.co.jp',
	'mirait-is.com',
	'ocha-kai.jp',
	'staging.bitkey.jp',
	'e.sbengineering.co.jp',
	'kokusaitoransu.jp',
#	'ozn.co.jp',	# deleted 2023-11-09
	'ohtaryu.co.jp',
	'futuredme.com',
	# added 2023-08-21
	'sej.jp',
	'faj.co.jp',
	'testkgis.com',
	'thmk.jp',
	'p-cluster.jp',
	'okinawatimes.net',
	'ryu-san-kyo.org',
	'jinji.conexio.co.jp',
	'matsue-ct.ac.jp',
	'japantimes.co.jp',
	'staff.adish.co.jp',
	'dmsgr.link',
	'hamee-webmarketing.work',
	'hospdata.jp',
	'fukuokacp.com',
	'gs4e.chubu.ac.jp',
	# added 2023-08-02
	's.do-johodai.ac.jp',
	'matsuo-inc.com',
	'ohmoto.local',
	'faj.jp',
	'mode-schedule.jp',
	'atsp.jp',
	'hjs.ed.jp',
	'practica.ooo',
	'ptb.or.jp',
	'rm-map.conexio.co.jp',
	'zaitakukanri.com',
	# added 2023-06-05
	'popn.net',
	's-on.jp',
	'kokoronomimi.jp',
	'appstair.com',
	'uniballclub.jp',
	'kjnext.jp',
	'trista.jp',
	'tmam-poc.com',
	'xy-en.net',
	'test.c.xy-en.net',
	# added 2023-05-10
	'ddd.co.jp',
	'yazutown.com',
	'satv.co.jp',
#	'kanseki.co.jp',		# deleted 2023-05-23
	'hyogo-u.ac.jp',
	'farmage.co.jp',
	'tfodev.jp',
	'zizai.co.jp',
	'jleagueproductions.jp',
	'itoshima-va.jp',
	'withd.co',
	'sakicorp.com',
	'cdt.co.jp',
	'vixen.co.jp',
	'mlc31924.jp',
	'nttls.biz',
	'janyken.com',
	'house-warranty.or.jp',
	'shield-agency.co.jp',
	'reikasai.jp',
	'fukui-joseikin.jp',
	'aip-global.com',
	'dangami-sannoh.co.jp',
	'jleague-kaigi.jp',
	'food-kr.com',
	'smartgame.jp',
	'smg-app.com',
	'demokankyo8888.com',
	'amsmedical.co.jp',
	'psychoreha.org',
	'iimunn.com',
	'baycurrent.jp',
	'lifull-mp.co.jp',
	'atumi-gr.co.jp',
	'g.torikyo.ed.jp',
	'smicagroup',
	'tfo.co.jp',
	'kaigoyoboucenter.org',
	# added 2023-03-29
	'taiko-net.co.jp',
	# added 2023-03-27
	'tadano.com',
	'focus.tax',
	'sakuraba.biz',
	'smz-products.co.jp',
	'komatsulite.co.jp',
	'yokohama-rf-konan.com',
	'odacvaa.com',
	'vehiclevision.jp',
	'dpl-project-fwx.com',
	'dsc-caster.info',
	'tanakakensetu.work',
	'finet.co.jp',
	# added 2023-02-20
	'ceq.co.jp',
	'pfa.or.jp',
	'jisedai.conexio.co.jp',
	'hoikushi-go.co.jp',
	'solcreate.com',
	'vixen.co.jp',
	'jleccs.com',
	'linktop.jp',
	'n-unist.co.jp',
	'spco-cloud.net',
	'enkinpro.com',
	'ceremonykiuchi.com',
	'times-adnext.co.jp',
	'mikado-denso.com',
	# added 2023-01-19
	'bandai.co.jp',
	'ultra-pay.co.jp',
	'leggendatech.co.jp',
	'mvc.jp',
	'g.kobe-kosen.ac.jp',
	'outdoor.sapporo-re.com',
	'amanabi.com',
	'nst-skh.co.jp',
	'chuo-besthome.co.jp',
	'shine-pro.jp',
	'cocoro-st.com',
	'leafnet.jp',
	'yamanashipremium.com',
	'dmmauto-biz.com',
	'influential-persons.jp',
	# added 2022-12-15
	#'yashima.jp',  # deleted 2022-12-20
	'miyamototest1.jp',
	'yamada-j.page',
	# added 2022-11-17
	'tam-bourine.co.jp',
	'miyamotoss.co.jp',
	'cq-group.jp',
	'effectplan.jp',
	'shonan-d.co.jp',
	'bellholdings.co.jp',
	'kunitachi.ac.jp',
	'suntecs.co.jp',
	'arigayadenki.co.jp',
	'taka-q.com',
	# added 2022-10-14
	'mediba.jp',
	'kamposol.biz',
	'joyfull.co.jp',
	'dcg.co.jp',
	'tttsetagayahoken.com',
	'akatsuki-estate.co.jp',
	'jibannet-bcpo.jp',
	'dsr-japan.com',
	'tokyo.dsr-japan.com',
	'ground-solution.co.jp',
	'qualicaps.co.jp',
	'dgft.jp',
	'htb-energy.com',
	# added 2022-09-20
	'il-nido.co',
	'japanagribio.co.jp',
	'coyote.fun',
	'tam-bourine.co.jp',
	'meat-ota.com',
	'rexa-m3.com',
	'liberal-solution.co.jp',
	'inest.co.jp',
	'pixel-spotlight.com',
	'e-spirit.jp',
	# added 2022-08-15
	'e-kougu.com',
	'iw-example.com',
	'willgate.co.jp',
	'i-will-opensource.jp',
	'jspto2021.com',
	'kawahara-group',
	#'shujitsu.ac.jp',  # deleted 2022-12-20
	#'htb-energy.com',  # deleted 2022-09-13
	'jrc-marinfonet.com',
	'ifcreate.co.jp',
	'tsuzuki.co.jp',
	'topy.co.jp',
	'ethic.jp',
	# added 2022-07-14
	'ryubo.co.jp',
	'sandabu.co.jp',
	'tokyobighouse.cloud',
	'plaza-e.co.jp',
	'co-dejima.jp',
	'glv.co.nz',
	'sboar.jp',
	'st.hiroo-koishikawa.ed.jp',
	'himiko.jp',
	'hoken-allgr.com',
	'wincube.co.jp',
	# added 2022-06-16
	'zeekstar.tokyo',
	# added 2022-06-15
	'human-abo.org',
	'cuc-id.com',
	'bee-music.jp',
	'plat-ease.co.jp',
	'orion-kikou.co.jp',
	'tohobs.co.jp',
	'buychemjapan.com',
	'trista.jp',
	# added 2022-05-17
	'suzuka-kokutai.jp',
	'ao-archi.com',
	'skycampus.jp',
	'yotsuba-k.or.jp',
	'profit-cube.co.jp',
	'repseminar.com',
	'musashino-music.ac.jp',
	'taodrive.com',
	'redhorse-group.com',
	'e4w.or.jp',
	'bizlink.io',
	'whiteaffiliate.biz',
	'gtest.conexio.co.jp',
	'stageinc.jp',
	'batstaff.jp',
	'ootoya.co.jp',
	'ishin-fukui.com',
	'rhtraveler.co.jp',
	't-time1500.jp',
	'my-japan.net',
	'nextup.jp',
	# added 2022-04-18
	'konicaminolta.com',
	'softflow.jp',
	'semitec',
	'securevdipoc.in',
	's-mugen.net',
	'mdtt.jp',
	'nestle-happyou.com',
	'j-bma.or.jp',
	'openloop.co.jp',
	'uluu-noen.jp',
	'daitochemical.com',
	#'jpmedsn.co.jp',		# deleted 2022-05-10
	'tsukumo.co.jp',
	'ohnishishoji.co.jp',
	'tanaka-rea.com',
	'aoba-tax.net',
	'key-cre.co.jp',
	'ubevaccine.jp',
	'erkennt.co.jp',
	'oneday-design.co.jp',
	'biore-uv.com',
	# added 2022-03-04
	'web-studio.tokyo',
	'fine-career.co.jp',
	'shufu.jp',
	'keimeikai.org',
	'bellsystem24.enterprise.slack.com',
	'bun-ko.jp',
	'matsuhaya.com',
	'pros-co.jp',
	'enomoto.ac.jp',
	'gr.kobunsha.cloud',
	'lifull-fam.com',
	'bizevent.jp',
	'm3ce.co.jp',
	'seedive.co.jp',
	'soshukai.jp',
	'housui.co.jp',
	'mal-vern.com',
	'ksyistm.xyz',
	'itm-cf.com',
	'securevdipoc.in',
#	'tokyobighouse.com',	# deleted 2023-11-06
	# added 2022-01-25
	'sodefuri.jp',
	'granmanibus.com',
	'ngkntk.co.jp',
	'daiki-axis.com',
	'open.kyoto.jp',
	'naa.jp',
	'skyarch.net',
	'tpx-japan.com',
	'marubeni-itsol.com',
	# added 2021-12-16
	'mwtcargo.com',
	'onecoinenglish.com',
	'fujitele.com',
	'ftcnetmate.com',
	'nihon-kankyo.jp',
	'lshare.jp',
	#'edukddi.com',		# deleted 2022-02-10
	'oki-printer.jp',
	'mmstokyo.co.jp',
	'toho-eps.com',
	'ub1table.jp',
	'lpga.or.jp',
	# added 2021-12-06
	'hhms.co.jp',
	'hankyu-ad.jp',
	# added 2021-11-10
	'ikeden.com',
	'f-furushima.com',
	'visasq.com',
	'takeuchihome.jp',
	'hrm.co.jp',
	'bcp.digiasset.co.jp',
	'td-gcp.com',
	'support.digiasset.co.jp',
	'uni-sax.com',
	'nms.nafco.co.jp',
	'ipet-ins.net',
	'japantravelcompany.com',
	'g-plan-test.net',
	'worksjapan.tech',
	'hiro-web.co.jp',
	# added 2021-10-04
	'enjoytokyo.jp',
	'tecnos.co.jp',
	'apaman-tokushima.com',
	'nextgen.co.jp',
	'japan-mercury.com',
	'shimokawa3791.com',
	#'musashino-music.ac.jp',	# deleted 2022-01-11
	'nekono-boo-chan.com',
	'bizcourt.space',
	'spaceapi.info',
	'kanpai.biz',
	'jsca.tokyo',
	'takuto-net.com',
	'hhp.co.jp',
	'bijicas.tomi103.net',
	'buychemjapan.jp',
	'ilab-inc.jp',
	'obihiro-ohtani.ed.jp',
	'asahipretec.my.salesforce.com',
	'especially.jp',
	'shutoken.net',
	'ken-navi.jp',
	'hamaphil.jp',
	'mpwa.chiba.jp',
	'kplus-icts-bid-dev.komatsu.co.jp',
	'himeji-cci.or.jp',
	# added 2021-08-11
	'next.animate-holdings.co.jp',
	'sne.co.jp',
	'anest-iwata.co.jp',
	'suzko.co.jp',
	'goldswan.co.jp',
	'tecnos-grp.com',
	'cdunited.net',
	'kinken-ex.com',
	'acceluniverse.com',
	'nelco.xyz',
	'enjoytokyo.jp',
	'ld-company.com',
	# added 2021-07-29
	'styles.jpn.com',
	'meiwa-sng.co.jp',
	'g.neec.ac.jp',
	'setubi-zumen.jp',
	'cresco.co.jp',
	'komc.co.jp',
	'verude.com',
	'f-motor.co.jp',
	'ysccloud.jp',
	'suite.itougumi.co.jp',
	'granmanibus.com',
	'hirama.info',
	'daito-g.jp',
	'apptli.co.jp',
	'tokyo-deli.jp',
	'seo-adult.jp',
	'y-sanki.co.jp',
	'finderss.jp',
	'jice.or.jp',
	'protech2004.jp',
	'tds-g.info',
	'arario.co.jp',
	'jokan.co.jp',
	# added 2021-06-15
	'shimadzu-ltd.jp',
	'gumi-europe.com',
	'willsmart.co.jp',
	'suwa-youchien.ed.jp',
	#'imi-cp.com',		# deleted 2021-11-17
	'credour.com',
	'morecareee.jp',
	'aguajapan.co.jp',
	'nmd.ltd',
	'maritimedisplay.co.jp',
	'tophome.co.jp',
	#'looop.co.jp',
	'oenejapan.com',
	'cw-fw.or.jp',
	'safercw.co.jp',
	'pensees.co.jp',
	'oaksbest.co.jp',
	'skcon.jp',
	'reqtc.com',
	# added 2021-05-06
	'cataract-developer.com',
	'hqj.co.jp',
	'orieinc.page',
	'gdrive.siliconstudio.co.jp',
	'siliconstudio.co.jp',
	'yumesora.org',
	'hecj.co.jp',
	'yamasui.co.jp',
	'sskklab.jp',
	'air-group.jp',
	'dogenzaka-lab.com',
	'enaces.com',
	'naked.co.jp',
	'daijo.shukutoku.ac.jp',
	'tokyo-newmarket.jp',
	'jtp.co.jp',
	'wing7.co.jp',
	'profit-cube.com',
	'coposystest.com',
	'okatuu.com',
	'chatlink-app.com',
	'app-yt.com',
	'd-pop.cslabs.biz',
	'novelabo.com',
	'token.jp',
	'ac-create.co.jp',
	'oaroar.com',
	'i-seifu.jp',
	'primvere-m.com',
	'careerbeat.jp',
	'lan-incubator.com',
	'jahi.jp',
	'ent.jmc.ne.jp',
	'japan-home.com',
	'spinnaker.or.jp',
	'brandingassociates.com',
	'd-pops.co.jp',
	# added 2021-03-31
	'nextlink.facebook.com',
	'growst.jp',
	'hansui.org',
	'sansys.biz',
	'koeimktg.co.jp',
	'n-amicus.com',
	'genichi.jeis-ict-dev.com',
	'test.tac-school.co.jp',
	# added 2021-02-19
	'hikarimiso.co.jp',
	'atgirl.jp',
	'hijirinogo.com',
	'fujielectric.com',
	'bell24.co.jp',
	'kawaiimuseum.net',
	'hoku-r.com',
	'workstc.co.jp',
	'daini-den.co.jp',
	'junglejapan.com',
	'ipet-ins.com',
	# added 2021-01-21
	'7seven7.jp',
	'uyeno-group.co.jp',
	'jmc-inc.jp',
	'dtd.co.jp',
	'gyosys.site',
	'potential-agent.com',
	'jectone.co.jp',
	'w20japan.com',
	'tokkibu.co.jp',
	'tesco.co.jp',
	'techshop.jp',
	'sg.properties.hankyu-hanshin.com',
	'takara-bio.com',
	'micjp.co.jp',
	'findoutput.co',
	'g.healthlink.co.jp',
	'worksjapan.work',
	'orange-petsitter.com',
	'shintopaint.co.jp',
	'worksjapan.co.jp',
	'stream-matabee.com',
	# added 2020-12-23
	'yamatane.co.jp',
	'imd-a.jp',
	'gsuite.4cast.co.jp',
	'naka-cargo.com',
	'irepairs-lab.com',
	'kninnovation.com',
	'feb-omotenashi-seminar.com',
	'kito.com',
	'g.hiqzen.com',
	'ryuushin.com',
	'afd-bpo.work',
	'ryuushinkai.life',
	'csfactory.co.jp',
	# added 2020-11-19
	'q-inculab.com',
	'dso.q-inculab.com',
	'dena.jp',
	'shimz.co.jp',
	'integriculture.jp',
	'medpeer.co.jp',
	'pla2pla.jp',
	'maria-casablanca.com',
	'funnelinc.tokyo',
	'kotoku-g.co.jp',
	'walkjapan.com',
	'yutenkai.net',
	'imk-holdings.co.jp',
	'aktsby7.com',
	# added 2020-10-13
#	'integralkk.com',		# deleted 2020-10-21
	'ast-tokyo.jp',
	'alpha-31.work',
	'solaniwa-onsen.com',
	'spnp-web-test.com',
	'm3career-net.jp',
	'lifebizpartners.co.jp',
	'universe.co.jp',
	'birdworks.co.jp',
	# added 2020-09-24
	'skylark.co.jp',
	'sys.st-grp.co.jp',
	'fujitaka-edp.com',
	'invy.com',
	'tomokiurakawa.ne.jp',
	'crystal-hall.co.jp',
	'877.co.jp',
	'taiyo-yuka.net',
	'kotorinoyu.jp',
	'mattech.co.jp',
	# added 2020-08-18
	'reeracoen.co.jp',
	'rksmigtest.com',
	'tocad.com.hk',
	'b-e-a-m.jp',
	'able-toua',
	'jorder.jp',
	'bizwel.jp',
	# added 2020-07-27
	'ms-sapporo.co.jp',
	'inose-ls.co.jp',
	'maruichikokan.co.jp',
	'gop.co.jp',
	'uv-wellness.com',
	'mhinc.jp',
	'kyoei-ss.co.jp',
	# added 2020-06-16
#	'softbrain.co.jp',		# deleted 2020-06-19
	'ai-pel.com',
	'firstcabin-st.com',
	'venus-comrade.co.jp',
	'en-light.co.jp',
	'everclean.jp',
	'mizunosangyo.com',
	'joho-nagasaki.or.jp',
	'takuramidan.com',
	'peace-net.jp',
	'fujita-kz.co.jp',
#	'sboar.jp',		# deleted 2020-06-18
#	'nextbeat.net',		# deleted 2023-06-23
	'every.toctoc.jp',
	# added 2020-05-15
	'rakusuri.co.jp',
	'kingrun.co.jp',
	'quarters.co.jp',
	'vietnam-aid.com',
	'ebalance.co.jp',
	'scsk-entverif',
	'cc.saga-u.ac.jp',
	'flexasseven.com',
	'heitanbase.com',
	'prodrone.jp',
	'e-kaikeijimusyo.com',
	'data-refinement.com',
	'foresee-net.com',
	'hakubaku.jp',
	'himawari.website',
	'himawari-sato.jp',
	'tapreal.co.jp',
	'3softbrain.com',
	'k2u-j.com',
	'ga-gauss.com',
	'j-max.info',
	'mff2020.sapporofactory.jp',
	'livela.jp',
	'4cast.co.jp',
	'soft-ex.jp',
	# added 2020-04-14
	'mind.co.jp',
	'g.softbank.co.jp',
#	'members.ne.jp',	# deleted 2020-01-13
	'joyzo.co.jp',
	'bni-tezutsu',
	'cdg.nisseiasb.co.jp',
	'g.mobigate.biz',
	'layup.co.jp',
	'trigger-corp.com',
	'trigger-corp.jp',
	'landtrust.co.jp',
	'pltc-test.com',
	# added 2020-03-24
	'rescho.co.jp',
	'mebix.co.jp',
	'asdf.cc',
	'jinzai-kenkyusho.co.jp',
	'hynesen.com',
	'nextop.asia',
	'nayutanet.jp',
	# added 2020-03-02
	'shizuokaonline.com',
	# added 2020-02-21
	'tokyu-cnst.co.jp',
	'reeracoen.com.hk',
	'yossix.co.jp',
	'ssk-osd.com',
	'willway-net.jp',
	'mabuchi-net.jp',
	'traderssec.com',
	'juken-goukaku.com',
	'ncf-corporation.com',
	'alo-biz.com',
	'bbst.co.jp',
	'dnavec-corp.com',
	'b1895.com',
	'ventureunited.jp',
	'ooaana.or.jp',
	'admedialab.jp',
	'minnakorea.jp',
	'vra.ntt-west.cloud',
	'ysec.jp',
	'nankaiplywood.co.jp',
	'seedom.co.jp',
	# added 2019-12-09
	'jvckenwood.com',
	'jlce.jp',
	'alo-store.com',
	'candeo-hotels.com',
	'imjp.co.jp',
	'maruemuworks.site',
	'hcc-jp.com',
	'rutherford.jp',
	'nuan.jp',
	'goma-books.co.jp',
	'imjp.ne.jp',
	'sorakoto.space',
	'woody3.jp',
	'kozmic.co.jp',
	'armonicos.com',
	# added 2019-11-06
	'nx-life.jp',
#	'members.ne.jp',	# deleted 2020-01-13
	'career-in.net',
	'naturalhouse.co.jp',
	'miyaji-eng.jp',
	'ratelier.co.jp',
	'enigmo.co.jp',
	'wrixon.net',
	'lecre.jp',
	'maruei-u.co.jp',
	'ifc-net.or.jp',
	'yumeya-jp.com',
	'kobeshipping-g.com',
	# added 2017-08-14
	'nisseikiden.jp',
	'systemcon.co.jp',
	'nizista.com',
	'tagatame.co.jp',
	'kenbiweb.com',
	'agb.co.jp',
	'aobaya.co.jp',
	# added 2017-07-10
	'apb-gcp-support.com',
	'sanwacomp.jp',
	'kce-academy.net',
	'emicnet.co.jp',
	'2017tokyo.jp',
	'g.kewpie-grp.jp',
	# added 2017-06-27
	'glv.net.au',
	'cv-ltd.com',
	'itabashi.aieiyoho.com',
	'toai.co.jp',
	'itx.link',
	'ecure.jp',
	'applibot.co.jp',
	'nex-e.co.jp',
	# added 2017-05-11
	'enoteca.co.jp',
	'kcnosai.or.jp',
	'bell-farm.jp',
	'lifesalon-ho.co.jp',
	'mktgdrive.com',
	'gu3.se',
	'm.glv.co.jp',
	'm-mls.ecars.co.jp',
	'officecom.jp',
	'venture.jp',
	'itcnetwork.co.jp',
#	'a-dec.co.jp',		# deleted 2023-11-14
#	'sold-out.co.jp',
	# added 2017-04-07
	#'aoi-pro.co.jp',		# deleted 2022-07-05
	'artifata.com',
	'adicc.or.jp',
	'joy.ne.jp',
	'kantsu.com',
	'jrtours.jp',
	# added 2017-03-08
	'zero-i.jp',
	'wakasu.co.jp',
	'datahotel.co.jp',
	'fastpath.jp',
	'bri.co.jp',
	'nskl.jp',
#	'shogi.or.jp',					# deleted 2017-08-14
	#'ml.legal-support-osaka.jp',	# deleted 2017-03-17
	'arbot.jp',
	'ghc-j.com',
	# added 2017-02-02
#	'labs.kokuyog.com',		# deleted 2019-12-11
	'v.gmo-sol.jp',
	'kamakura-net.co.jp',
	'it-sansan.com',
	'toyota-kobe.ac.jp',
	'wannacome.jp',
	'visunario.com',
	'lastresort.co.jp',
	'qlt.co.jp',
	'otafukufoods.com',
	'ccgmail.jp',
	'prosolve.jp',
	'sekoukijun.misawa.co.jp',
	'globridge.co.jp',
	'geo-code.co.jp',
	'fujikikai-inc.co.jp',
	'lofficiel.jp',
	'nextapps.com',
	# added 2016-12-19
#	'japantravelcompany.com',	# deleted 2017-01-25
#	'walkjapan.com',			# deleted 2017-01-25
	# added 2016-12-08
	'saitoseiki.co.jp',
	'otabe.co.jp',
	'aderans.com',
	'reno.co.jp',
	'aes-jp.co.jp',
	# added 2016-11-08
	'mbsm.info',
	'fibest.com',
	'me-rise.com',
	'kohkun.go.jp',
	'alaya.co.jp',
	'g2g.jp',
	'jib-home.jp',
	'nhn-techorus.com',
	'hekiun.co.jp',
	'sevenmedia.jp',
	'miuraz.com',
	# added 2016-10-11
	'cubic-hd.co.jp',
	'cio-sansan.com',
	'cio-33i.com',
	'keiozu.biz',
	'n-system.mobi',
	'dowell.co.jp',
	'indevice.co.jp',
	'sumai-net.jp',
	'pokelabo.co.jp',
	# added 2016-09-20
	'storia-wedding.jp',
	'tenpura-kuruma.com',
	'kumapon.tokyo',
	'hokutoeng.co.jp',
	'fnets-gw.net',
	'metrofood.co.jp',
	'mike-iwasaki.co.jp',
	'enpachi.co.jp',
	'okayama.mpuni.co.jp',
	# added 2016-08-09
	'acaric.co.jp',
	'vix.co.jp',
	'thealthcare.jp',
#	'tokyo-shoseki.co.jp',		# deleted 2017-11-22
	'kahosyo.com',
	'watayama.info',
	'ysknet.co.jp',
	'science-t.com',
	'fuji-kagaku.co.jp',
	'opusdesign.com',
	# added 2016-07-04
	'apps.asics.co.jp',
	'sjad.co.jp',
	'is-on.co.jp',
	'ga.fujifilm-software.co.jp',
	'g.soliton.co.jp',
	# added 2016-06-02
	'adseainnovation.com',
	'aac.co.jp',
	'ophd.co.jp',
	'oneup-inc.com',
#	'sbdevelop.com',  # deleted 2016-08-31
	'wiztec.co.jp',
	# added 2016-05-12
#	'geonet.co.jp',  # deleted 2018-12-21
	'f1media.co.jp',
	'mediagene.co.jp',
	'takashijuku.com',
	'daisostore.com',
	'okn3.com',
	# added 2016-04-14
	'nicnet.co.jp',
	'unioncorp.co.jp',
	'sn21.jp',
	'hoikushi-eclub.com',
	'techorus.com',
	'satosys.jp',
	'aic-co.jp',
	# added 2016-03-14
	'n-monitor.co.jp',
	'fujitsu-general.com',
	'airman.co.jp',
	'f11ri.fujielectric.com',
	'amana.jp',
	'bestbuy-smile.biz',
	'horizon-e.co.jp',
	'ec-orange.jp',
	'scbm.jp',
	'yamane-d.co.jp',
	's-lcd.jp',
	'373news.com',
	'meiwainc.co.jp',
	# added 2016-02-03
	'min2miel.com',
	'invite-corp.com',
	'next-marke.jp',
	's-cubism.jp',
	'y-apps.net',
	'naitei-bank.jp',
	's-gr.jp',
	's-ml.jp',
	'propertydbk.com',
	'vcnet.jp',
	'yashima-co.co.jp',
	# added 2016-01-05
	'nomura-system.co.jp',
	'fpbrain.co.jp',
	'shop.s-cubism.jp',
	'fomcontents.biz',
	'daiwaodakyu.co.jp',
	'di-marketing.com.vn',
	'shelfs.jp',
	'apps.itougumi.co.jp',
	'nichibenren.or.jp',
	'sc-tsusho.jp',
	'richgene.co.jp',
	'cxmaster.com',
	'rt-appstest.jp',
	's-k-eng.jp',
	't.coacha.com',
	'mcpc-jp.jp',
	'leoc.co.jp',
	# added 2015-12-02
	'forval.co.jp',
	'bakasvvr.jp',
#	'datahotel.co.jp',  # deleted 2016-02-12
	'vanfu.co.jp',
	'threelight.co.jp',
	'payment.deals',
	'global.alc.co.jp',
	'kusakanmuri.com',
	'usei.jp',
	'agress.co.jp',
	'aics-gapps.co.jp',
#	'nsk-net.co.jp',  # deleted 2021-07-14
	'otowadenki.com',
	'w-int.jp',
	# added 2015-11-11
	'asakawahome.com',
	'surf-inc.jp',
	'icecap.co.jp',
	'miuraz.com',
	'cube-c.com',
	'nakagami-inc.com',
	'flave.co.jp',
	'scomms.jp',
	'testlandnet.net',
	's-energy.co.jp',
	'calm-design.net',
	'hit-ad.co.jp',
	# added 2015-10-02
	'mui-ec.muramoto.com',
	'miyaji-eng.co.jp',
	'yakuji.co.jp',
	'redhorse-trust.com',
	'ogata-cie.com',
	'prima-rire.co.jp',
	'm-glory.jp',
	'realcloud.jp',
	'sbc-test.com',
	# added 2015-09-17
#	'hcfm.jp',			# deleted 2019-11-06
	'smikiegames.com',
	'aics.co.jp',
	'yellowtails.co.jp',
	'sionnet.co.jp',
	'toylogic.co.jp',
	'ipl-soft.co.jp',
	'seedseed.co.jp',
	'hachicli.or.jp',
	'ctd.jp',
	'okifun.com',
	'shikatanaka.com',
	'kurux2.org',
	'g.nissui.co.jp',
	'ga.menard.co.jp',
	'okinawa-u.ac.jp',
	'eiwa-net.co.jp',
	'createch.jp',
	'eyesaac.com',
	'zeirishinet.com',
	'crestec.jp',
	'e-associates.co.jp',
	'dreamlife.co.jp',
	'gokuu.net',
	'hamadasyuzou.co.jp',
	'el.s-cubism.jp',
	'axas.co.jp',
	'g.s-cubism.jp',
	'green-i.co.jp',
	'3ms.co.jp',
	'az-hd.co.jp',
	'tech.s-cubism.jp',
	'gate.nihonkijun.jp',
	'tokyogumi.com',
	'aspesi.co.jp',
	'dckkgroup.com',
	'observecom.jp',
	'artpresto.net',
	'caps-inc.jp',
	'bebit.co.jp',
	'satinc.co.jp',
	'sp-agency.net',
	'astant.com',
	'metaworks.jp',
	'abot.io',
	'thealthcare.co.jp',
	'peacemind-jeap.co.jp',
	'svt-c.com',
	'rococo.co.jp',
	'yanmar-globalsys.com',
	'imj-cosmo.net',
	'hokko.com',
	'gatenihonkijun.jp',
	'miraijushi.net',
	'uiassets.com',
	'hearzest.co.jp',
	'itarchitects.co.jp',
	'ms.mbs-net.co.jp',
	'labozoo.com',
	'yamazakipan.co.jp',
	'doggyman.co.jp',
	'mgmtsol.co.jp',
	'iida-tusho.co.jp',
	'united-c.co.jp',
	'mtlop.co.jp',
	'skyvision.co.jp',
	'estgroup.jp',
	'vdragon.co.jp',
	'b2b-event.com',
	#'kbc.jp',		# deleted 2022-09-02
	'neetec.co.jp',
	'tokairiken.co.jp',
	'gtest.toyotahome.co.jp',
	'nitto-optical.co.jp',
	'einstein-net.co.jp',
	'carchive.com',
	'paon.co.jp',
	'observe.co.jp',
	'bizwel.jp',
	'aime.co.jp',
	'hounichi.com',
	'resystem.co.jp',
	'globeride.biz',
	'nihonkijun.jp',
	'food.s-cubism.jp',
	'hikari-takatsuki.jp',
	'pitali.jp',
	'llamasoftasia.biz',
	'mpra.jp',
	'morisawa.co.jp',
	'waggle-mk.com',
	's-marke.jp',
	'4any.bc-glex.net',
	'cecl.biz',
	'dipsol.co.jp',
	'synnexinfotec.co.jp',
	'sic-net.co.jp',
	'comvex.co.jp',
	'hapicla.com',
	'alphacox.com',
	'iso-caf.net',
	'rokumeido.net',
	'mybanker.co.jp',
	'p-baru.co.jp',
	'saikoudou.com',
	'trend-and-supply.com',
	'belle-lumiere.com',
	'good-style-company.com',
	# added 2014-12-10
	'mscl-east.co.jp',
	'birth-inc.co.jp',
	'ggii.co.jp',
	'eqs.jp',
	'taikisha.co.th',
	'care-taxi.info',
	'nittsu-hikkoshi.com',
	'korome.gr.jp',
	# added 2014-11-13
	'with-co.jp',
	'iwaicosmobs.biz',
	'dcme-union.com',
	'pixela.jp',
#	'birth.co.jp',	# deleted 2014-12-15
	'central-con.co.jp',
	'aqua-web.co.jp',
	'l-arrange.co.jp',
	'vm.sony.com',
	'takacom.co.jp',
	'csnext.mobi',
	'mile-stone.jp',
	'zaimu.com',
	# added 2014-10-14
	'vip-soft.jp',
	'uls-corp.jp',
	'sales.step-inet.jp',
	'machidajimusho.com',
	'techno-site.net',
	'linksolution.co.jp',
	'zao2138.com',
	'wakayanagi.info',
	'netstar-inc.org',
	'haramachicci.com',
	'tomeminami.info',
	'kanan-m.info',
	'totsumedia.jp',
	# added 2014-09-16
	'rakuenprj.jp',
	'mcp-sec.com',
	'ekanto.mpuni.co.jp',
	'pub-hub.com',
	'gapps.chugai-pharm.co.jp',
	'assistnet2000.com',
	'flm.co.jp',
	'frestar.co.jp',
	# added 2014-08-19
	'nitta-group.com',
	'dynaxt.co.jp',
	'ga.rbcontrols.co.jp',
	'ga.emori.co.jp',
	'i.quick.co.jp',
	'ashulla-works.com',
	'ici-sports.jp',
	'technosite-tokyo.com',
	'osawa-inc.co.jp',
	'itcn-usa.com',
	'uzushio-hd.com',
	# added 2014-07-08
	'reraku.co.jp',
	'esplink.me',
	'mtnet.co.jp',
	'jsma.or.jp',
	'nihonzaitaku.net',
	'buffalotechbrasil.com.br',
#	'acaric.co.jp',		# deleted 2015-03-27
	'cosmos-ss.co.jp',
	'jreast-omiya.com',
	'test.toyogosei.co.jp',
	'lpca.jp',
	'hoko-express.co.jp',
	'jun.co.jp',
	# added 2014-06-10
	'efmarketing.jp',
	'seiko-giken.jp',
	'yuki-field.co.jp',
	'cocolofull.jp',
	'casleyconsulting.co.jp',
	'sunnyteru.com',
	'nissin5111.com',
	# added 2014-05-14
	'done.co.jp',
	'test-flexsystems-inc.mobi',
	'nissoshoji-mobil.jp',
	'travelpress.jp',
	'santa-chiara.jp',
	'miyosi.co.jp',
	'test.nippon-seiki.co.jp',
	'savaway.jp',
	'gm.daikoku.co.jp',
	'f-b-s.jp',
	'obayashi.com',
	'foc-cloud.com',
	'sophialight.co.jp',
	'nkgfan.co.jp',
	'tadanog.co.jp',
	'otacute.com',
	'openkit.com',
	'everg.co.jp',
	'pubridge.jp',
	'unitedsearch.jp',
	'hisamatsu.net',
	'sfs.co.jp',
	'alohastandards.com',
	'fujifilmkyowakirin-biologics.com',
	'togyu.jp',
	'sem-tky.info',
	'corestaff.co.jp',
#	'jmc-inc.jp',		# deleted 2019-11-06
	'ugsugs.mobi',
	# added 2014-02-18
	'yonbyoukyou.jp',
	'cemedine.co.jp',
	'e-shihoushoshi.com',
	# added 2014-01-31
#	'mimaki.jp',		# deleted 2015-02-04
	# added 2014-01-08
	'spri300.jp',
	'gtd.co.jp',
	'bright.bz',
	'lalba.co.jp',
	'will-systems.com',
	'nbcw.co.jp',
	'trso.co.jp',
	'j-line.co.jp',
	'thestirrers.com',
	'lite-on.co.jp',
	'fines-net.com',
#	'm3career.com',		# deleted 2014-09-24
	# added 2014-01-04
	'fujifilm.com',
	'jokatsu.com',
	'ga.fujifilm-software.co.jp',
	'fujifilm10.mygbiz.com',
	# added 2013-12-17
	'codestart.jp',
	'upp-its.com',
	'gapps.ynl-it.biz',
	'mitsui-soko-air.com',
	'j-coach.com',
	'appstest.itcnetwork.co.jp',
	'phos-iridos.com',
	'okamotonet.co.jp',
	'good-egg.jp',
	'maguro-yamasa.com',
	'sprox.co.jp',
	# added 2013-11-07
	'annex-rv.co.jp',
	'saiyo.seijo.co.jp',
	'daisodev.com',
	'ishikawa-hsp.net',
	'itcndemo.info',
	'iscompany.net',
	'sun-denshi.co.jp',
#	'freshnessburger.co.jp',	# deleted 2014-07-16
	'bellkey.com',
	'daiwa-kasei.co.jp',
#	'nsrolls.co.jp',			# deleted 2017-11-14
	'namiki-group.com',
	'inomatakensetsu.co.jp',
	're-creo.jp',
	'okinawa-longstay.com',
	'ootoya.biz',
	'oishikobe.com',
#	'kusukame.com',		# deleted 2013-11-19
	# added 2013-09-09
	'g.ykkap.co.jp',
	'sshikoku.mpuni.co.jp',
	'smail.flm.co.jp',
	'varuna.jp',
	'off180.com',
	'g.inaba.co.jp',
	'the-company.jp',
	# added 2013-08-07
	'csetest.info',
	'tensodo.co.jp',
	'technosmile.co.jp',
	'kokuyo-g.com',
	'hitachi-displays.com',
	'cseinfo.co.jp',
	'sys.sthdg.co.jp',
	'alibaba-inc.jp',
	'asd-apps.com',
	# added 2013-07-25
#	'kusuri-aoki.com',		# deleted 2023-04-25
	# added 2013-07-09
	'tokyu-land.jp',
#	'oisix.co.jp',		# deleted 2014-09-08
	's.m-academia.co.jp',
	'miyake-asia.com',
#	'fuji-kankyo-s.co.jp',		# deleted 2020-06-04
	'meiwa.jp',
	'trustsystem.co.jp',
	'itcn-korea.com',
	'g.niitaka.co.jp',
	'n-ttr.net',
	'dla.co.jp',
	'soljence.co.jp',
	# added 2013-06-10
	'hired.co.jp',
	'terilogy.net',
	'atsp.co.jp',
	'obara-medicalservice.jp',
	'coach.co.jp',
	# added 2013-05-15
	'dev.sthdg.co.jp',
	'sync.fm',
	'itghd.jp',
	'ggsmail.jp',
	'olive.co.jp',
	'shufunotomo.co.jp',
	'fp1.co.jp',
	'opus-award.com',
	'global-associates.jp',
	'sun-denshi.jp',
	'toyoseal.com',
	'freeport.co.jp',
	'fncs.jp',
	# added 2013-04-24
#	'casleyconsulting.co.jp',	# deleted 2013-05-08
	# added 2013-04-18
	'uppartners.net',
	'ecosupport.biz',
	'ir-g.jp',
	'ura71.com',
	'sunstargame.com',
	'fgicp.com',
	'archibox.co.jp',
	'omicjpn.com',
	'ic-net-cs.com',
	'comnet-network.co.jp',
	'kamei-net.co.jp',
	'ps-grp.com',
	'sbir.jp',
	'bisya.jp',
	'g.vio.ne.jp',
	'dln.jp',
	'ppcjcorp.com',
	'nokioo.jp',
	'sister-link-bebe.com',
	'ksnosai.or.jp',
	'calladoc.jp',
	'ubil.jp',
	'acty-eng.co.jp',
	'agress.jp',
	'ga-style.jp',
	'systx.co.jp',
	'dev.shoeisha.jp',
	'fitlink.co.jp',
	'rmobile.co.jp',
	'takenaka.co.jp',
	'dyna-tech.co.jp',
	'ekimae-implant.jp',
	'ebisucat.com',
	'nikkol.co.jp',
	'ppcj.co.jp',
	'bellsonica.co.jp',
	'river-ele.co.jp',
	'frm.netseiho.com',
	'tentsubu.com',
	'buffalo-sa.jp',
	'jsk02.info',
	'egao39.com',
	'lca-holdings.co.jp',
	'nttdata-beenchina.com',
	'tsuzuki-densan.co.jp',
	'test.nikon.com',
	'deltawing.co.jp',
	'g-laffite.info',
	'kakuei-gas.com',
	'fastone.co.jp',
	'kichiri.co.jp',
	'gtest.ponycanyon.co.jp',
	'kobe-cmp.com',
#	'okco.jp',		# deleted 2016-07-21
	'ajis-group.com',
	'unitygs.info',
	'up-date.ne.jp',
	'ndc-group.co.jp',
	'kobe-cmp.com',
	'lci-italia.com',
	'ngigroup.com',
	'alasa.co.jp',
	'sailing.ne.jp',
	'acone.jp',
	'assetprime.co.jp',
	'area-crs.com',
	'iso-arc.net',
	'chiyoda-sushi.biz',
	'fmyame.jp',
	'labeau.co.jp',
	'ragtokyo.co.jp',
	'orionkkk.co.jp',
	'miyata-takatuki.co.jp',
	'findway.jp',
	'retailmate.co.jp',
	'lalala-saga.co.jp',
	'parasa-x.com',
	'qlync2.com',
	'u23.jp',
	'kugahara-bc.com',
	'euglena.jp',
	'acsapps.jp',
	'ascendia.jp',
	'cyberstep.com',
	'rescuenetwork.co.jp',
	'bobson.co.jp',
	'shokuiki-site.com',
	'ipros.jp',
	# added 2013-02-20
	'apps.asics.co.jp',
	'asics.co.jp',
	# added 2012-12-07
	'palsystem-tokyo.or.jp',
	# added 2012-11-22
	'makotrax.com',
	# added 2012-10-01
	#'dairiki.co.jp',		# deleted 2023-01-19
	'kamigumi.co.jp',
	# added 2012-08-24 
	'been-service.co.jp',
	'nttdata-been.co.jp',
#	'asdf.cc',				# deleted 2018-02-05
	# added 2012-08-01
#	'jet-t.co.jp',			# deleted 2019-11-06
#	'qualica.co.jp',		# deleted 2018-06-18
	'hamaphil.jp',
#	'tajima-roof.co.jp',	# deleted 2012-07-26
	'japio.jp',
	'f-tax.com',
	'zappallas.com',
	'trio.co.jp',
	'infobahn.co.jp',
	'kb-wg-test.com',
	'i-service.asia',
	'djcom.jp',
	'speedrich.com',
	'ideas-co.com',
	'tmeds.co.jp',
	'doinet.co.jp',
#	'asahikasai.co.jp',		# deleted 2013-01-08
	'adept-hair.com',
	'tequila-c.com',
	'ebisu.in',
	'lynx-biz.com',
	'telemex.org',
	'pullcm.jp',
	'avenir-home.com',
	'fractalist.jp',
	'macrolab.co.jp',
	'ins-g.net',
	'ebisuflag.com',
	'ebisushop.com',
	'fuji-inds.com',
	'idea-village.com',
	'10sei.com',
#	'fujisash.co.jp',		# deleted 2013-07-09
	'as-works.co.jp',
	'iidagroup.net',
	'harakosan.co.jp',
	'starbucks.co.jp',
	'tc-relation.jp',
	'silky-style.com',
	'triog.co.jp',
	'johnan.com',
	'tokkari.com',
	'ooeda-vc.com',
	'step.ac',
	'address-web.co.jp',
	'staffportal.net',
	'mk-ele.co.jp',
	'fakes.jp',
	'assetworks.jp',
	'human-inc.jp',
	'personalize.jp',
	'g.green-i.co.jp',
	'sonic-obihiro.com',
	'filce.jp',
	'asw-net.com',
	'g.unimat-life.co.jp',
	'qbizadm.com',
	'miurabay.co.cc',
	'saijk.or.jp',
	'mobilefelica.com',
	'alphaplanning.co.jp',
	'moumaku.com',
	'splash-eiki.jp',
	'links-mktg.co.jp',
	'cj-system.net',
	'id-s.info',
	'itochuauto.jp',
	'seams.biz',
	'yuusei.or.jp',
	'webagency.jp',
	'mobile-system.co.jp',
	'mhs.co.jp',
	'paris-kanko.com',
	'apt.kkc-hd.com',
	'mocal-edu.org',
	'hitoduma04510.com',
	'kobe-king.jp',
	'princess-work.com',
	'glm.co.jp',
	'taiyo-p.co.jp',
	'cresco.jp',
	'seedinc.co.jp',
	'tbss.co.jp',
	'daieikai.com',
	'jdi.co.jp',
	'mail.tsumura.co.jp',
	'cleansys.ne.jp',
	'waterwater.co.jp',
	'jp.nikon.com',
	'excellent.ne.jp',
	'ccs-inc.co.jp',
#	'kansai-ssol.co.jp',	# deleted 2013-11-02
	'oakvillagemgt.jp',
	'taxconsultant.jp',
	'pilotink.jp',
#	'tdn.co.jp',	# deleted 2021-10-04
	'nippondenko.co.jp',
	'ictbs.co.jp',
	'mmnet.co.jp',
	'newtonworks.jp',
	'ranagroup.jp',
#	'tocad.co.jp',		# deleted 2014-05-01
	'acquire.co.jp',
	'apoplus-cso.com',
	'systx.co',
	'tv-tokyo.co.jp',
	'kokuyo.co.jp',
	'tokyu-land.co.jp',
]
